# Generated by Django 4.0.6 on 2022-07-19 17:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('modified_at', models.DateTimeField(verbose_name='date modified')),
                ('category', models.CharField(choices=[('M', 'Men'), ('WM', 'Women'), ('K', 'Kids')], default='WM', max_length=30)),
                ('types', models.CharField(choices=[('C', 'Casual'), ('FR', 'Formal'), ('SP', 'Sport')], default='C', max_length=30)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('vendor', models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('status', models.SmallIntegerField(choices=[(1, 'preparing'), (2, 'Ready'), (3, 'Delivering'), (4, 'Delivered')], default=1)),
                ('total_price', models.PositiveIntegerField()),
                ('isdiscount', models.BooleanField()),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=10, null=True)),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.CharField(max_length=500, null=True)),
                ('user', models.CharField(max_length=25)),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.item')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.item')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.order')),
            ],
        ),
    ]
