# Generated by Django 4.0.6 on 2022-07-20 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.vendor'),
        ),
    ]
