# Generated by Django 4.0.6 on 2022-07-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='costumer',
            new_name='customer',
        ),
    ]
