# Generated by Django 4.0.6 on 2022-07-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_order_discount_alter_order_isdiscount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'preparing'), (2, 'Ready'), (3, 'Delivering'), (4, 'Delivered')], default=1),
        ),
    ]
