# Generated by Django 4.0.6 on 2022-07-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'preparing'), (2, 'Ready'), (3, 'Delivering'), (4, 'Delivered'), (-1, 'Cancelled'), (0, 'Pending')], default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Accepted'), (2, 'Ready for delivery'), (3, 'Delivering'), (4, 'Delivered'), (-1, 'Cancelled'), (0, 'Pending')], default=1),
        ),
    ]
