# Generated by Django 4.0.6 on 2022-07-23 13:19

from django.db import migrations, models
import shopping.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_alter_order_status_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=shopping.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Accepted'), (2, 'Ready for delivery'), (3, 'Delivering'), (4, 'Delivered'), (-1, 'Cancelled'), (0, 'Pending')], default=0),
        ),
    ]
